//data only - array. No functions here.
//this file MUST be loaded BEFORE app.js.

/* -------------------------------------------
   Quotes: keep each item as "text<br><br>Author"
   app.js will split and sanitize for display.
-------------------------------------------- */
window.quotes = [
    'It does not matter how slowly you go as long as you do not stop.<br><br>Confucius',
    'If you don\'t go after what you want, you\'ll never have it. If you don\'t ask, the answer is always no. If you don\'t step forward, you\'re always in the same place.<br><br>Nora Roberts',
    'Begin with the end in mind.<br><br>Stephen Covey',
    'Too many of us are not living our dreams because we are living our fears.<br><br>Les Brown',
    'The difference between a successful person and others is not a lack of strength or a lack of knowledge, but rather a lack of will.<br><br>Vince Lombardi',
    'Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don\'t quit.<br><br>Conrad Hilton',
    'If you hear a voice within you say \'you cannot paint,\' then by all means paint, and that voice will be silenced.<br><br>Vincent van Gogh',
    'The surest way not to fail is to determine to succeed.<br><br>Richard Brinsley Sheridan',
    'Desire is the starting point of all achievement—not a hope, not a wish, but a keen pulsating desire, which transcends everything.<br><br>Napoleon Hill',
    'A computer once beat me at chess, but it was no match for me at kickboxing.<br><br>Emo Philips',
    'Whether I fail or succeed shall be no man\'s doing but my own. I am the force.<br><br>Elaine Maxwell',
    'To find a fault is easy; to do better may be difficult.<br><br>Plutarch',
    'To give yourself the best possible chance of playing to your potential, you must prepare for every eventuality. That means practice.<br><br>Seve Ballesteros',
    'To handle yourself, use your head; to handle others, use your heart.<br><br>Donald Laird',
    'To think creatively, we must be able to look afresh at what we normally take for granted.<br><br>George Kneller',
    'We all have ability. The difference is how we use it.<br><br>Stevie Wonder',
    'To succeed you need to find something to hold on to, something to motivate you, something to inspire you.<br><br>Tony Dorsett',
    'Things which matter most must never be at the mercy of things which matter least.<br><br>Johann Wolfgang von Goethe',
    'Wherever you go, go with all your heart.<br><br>Confucius',
    'Every day is a journey, and the journey itself is home.<br><br>Matsuo Bashō',
    'A good traveler has no fixed plans and is not intent on arriving.<br><br>Lao Tzu',
    'The pessimist sees difficulty in every opportunity; the optimist sees the opportunity in every difficulty.<br><br>Winston Churchill',
    'Don\'t let yesterday take up too much of today.<br><br>Will Rogers',
    'It\'s not whether you get knocked down; it\'s whether you get up.<br><br>Vince Lombardi',
    'If you are working on something exciting that you really care about, you don\'t have to be pushed. The vision pulls you.<br><br>Steve Jobs',
    'Whether you think you can or think you can\'t, you\'re right.<br><br>Henry Ford',
    'The only limit to our realization of tomorrow will be our doubts of today.<br><br>Franklin D. Roosevelt',
    'Creativity is intelligence having fun.<br><br>Albert Einstein',
    'You are never too old to set another goal or to dream a new dream.<br><br>C. S. Lewis',
    'Today\'s accomplishments were yesterday\'s impossibilities.<br><br>Robert H. Schuller',
    'If you haven\'t found it yet, keep looking. Don\'t settle.<br><br>Steve Jobs',
    'Perpetual optimism is a force multiplier.<br><br>Colin Powell',
    'Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength.<br><br>Arnold Schwarzenegger',
    'The world breaks everyone, and afterward, some are strong at the broken places.<br><br>Ernest Hemingway',
    'A truly strong person does not need the approval of others any more than a lion needs the approval of sheep.<br><br>Vernon Howard',
    'There are better starters than me, but I\'m a strong finisher.<br><br>Usain Bolt',
    'He who believes is strong. He who doubts is weak. Strong convictions precede great actions.<br><br>Louisa May Alcott',
    'Strength and growth come only through continuous effort and struggle.<br><br>Napoleon Hill',
    'Tough times never last, but tough people do.<br><br>Robert H. Schuller',
    'I believe that tomorrow is another day.<br><br>Audrey Hepburn',
    'That which does not kill us makes us stronger.<br><br>Friedrich Nietzsche',
    'If you are not willing to risk the usual, you will have to settle for the ordinary.<br><br>Jim Rohn',
    'Either write something worth reading or do something worth writing.<br><br>Benjamin Franklin',
    'You may be disappointed if you fail, but you are doomed if you don\'t try.<br><br>Beverly Sills',
    'Dream big and dare to fail.<br><br>Norman Vaughan',
    'Build your own dreams, or someone else will hire you to build theirs.<br><br>Farrah Gray',
    'I would rather die of passion than of boredom.<br><br>Vincent van Gogh',
    'I didn\'t fail the test. I just found 100 ways to do it wrong.<br><br>Benjamin Franklin',
    'Limitations live only in our minds, but if we use our imaginations, our possibilities become limitless.<br><br>Jamie Paolinetti',
    'Challenges are what make life interesting, and overcoming them is what makes life meaningful.<br><br>Joshua J. Marine',
    'Happiness is not something ready-made. It comes from your own actions.<br><br>Dalai Lama',
    'The best revenge is massive success.<br><br>Frank Sinatra',
    'Either you run the day or the day runs you.<br><br>Jim Rohn',
    'All our dreams can come true if we have the courage to pursue them.<br><br>Walt Disney',
    'If you cannot do great things, do small things in a great way.<br><br>Napoleon Hill',
    'An obstacle is often a stepping stone.<br><br>William Prescott',
    'The journey of a thousand miles begins with one step.<br><br>Lao Tzu',
    'What you do speaks so loudly that I cannot hear what you say.<br><br>Ralph Waldo Emerson',
    'The best way out is always through.<br><br>Robert Frost',
    'Keep your face to the sunshine and you will never see the shadows.<br><br>Helen Keller',
    'The best dreams happen when you\'re awake.<br><br>Cherie Gilderbloom',
    'The difference between ordinary and extraordinary is that little extra.<br><br>Jimmy Johnson',
    'You must not only aim right, but draw the bow with all your might.<br><br>Henry David Thoreau',
    'Even if you\'re on the right track, you\'ll get run over if you just sit there.<br><br>Will Rogers',
    'Every strike brings me closer to the next home run.<br><br>Babe Ruth',
    'A year from now you may wish you had started today.<br><br>Karen Lamb',
    'If there is no struggle, there is no progress.<br><br>Frederick Douglass',
    'What we fear doing most is usually what we most need to do.<br><br>Tim Ferriss',
    'Your imagination is your preview of life\'s coming attractions.<br><br>Albert Einstein',
    'Even if you fall on your face, you\'re still moving forward.<br><br>Victor Kiam',
    'The purpose of our lives is to be happy.<br><br>Dalai Lama',
    'The dreamers are the saviors of the world.<br><br>James Allen',
    'Change your thoughts and you change your world.<br><br>Norman Vincent Peale',
    'Action is the foundational key to all success.<br><br>Pablo Picasso',
    'I will go anywhere, provided it be forward.<br><br>David Livingstone',
    'Never let your memories be greater than your dreams.<br><br>Doug Ivester',
    'The greatest discovery of my generation is that a human being can alter his life by altering the attitudes of his mind.<br><br>William James',
    'The aim of an argument or discussion should not be victory, but progress.<br><br>Joseph Joubert',
    'Only those who will risk going too far can possibly find out how far one can go.<br><br>T. S. Eliot',
    'To live is the rarest thing in the world. Most people exist; that is all.<br><br>Oscar Wilde',
    'Freedom is not the absence of commitments, but the ability to choose yours.<br><br>Paulo Coelho',
    'Conformity is the jailer of freedom and the enemy of growth.<br><br>John F. Kennedy',
    'Every man dies, but not every man really lives.<br><br>William Wallace',
    'Nothing important was ever achieved without someone taking a chance.<br><br>H. Jackson Brown, Jr.',
    'Success is walking from failure to failure with no loss of enthusiasm.<br><br>Winston Churchill',
    'Opportunities don\'t happen; you create them.<br><br>Chris Grosser',
    'Try not to become a person of success, but rather try to become a person of value.<br><br>Albert Einstein',
    'No one can make you feel inferior without your consent.<br><br>Eleanor Roosevelt',
    'If you\'re going through hell, keep going.<br><br>Winston Churchill',
    'What seems to us as bitter trials are often blessings in disguise.<br><br>Oscar Wilde',
    'The distance between insanity and genius is measured only by success.<br><br>Bruce Feirstein',
    'Don\'t be afraid to give up the good to go for the great.<br><br>John D. Rockefeller',
    'Innovation distinguishes between a leader and a follower.<br><br>Steve Jobs',
    'There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.<br><br>Ray Goforth',
    'The starting point of all achievement is desire.<br><br>Napoleon Hill',
    'Courage is resistance to fear, mastery of fear—not absence of fear.<br><br>Mark Twain',
    'A real entrepreneur is somebody who has no safety net underneath them.<br><br>Henry Kravis',
    'The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.<br><br>Mark Caine',
    'Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.<br><br>Dale Carnegie',
    'Don\'t let the fear of losing be greater than the excitement of winning.<br><br>Robert Kiyosaki',
    'To accomplish great things, we must not only act, but also dream; not only plan, but also believe.<br><br>Anatole France',
    'It is better to fail in originality than to succeed in imitation.<br><br>Herman Melville',
    'The only thing standing between you and your goal is the story you keep telling yourself as to why you can\'t achieve it.<br><br>Jordan Belfort',
    'You can\'t build a reputation on what you are going to do.<br><br>Henry Ford',
    'When someone tells me "no," it doesn\'t mean I can\'t do it; it simply means I can\'t do it with them.<br><br>Karen E. Quinones Miller',
    'Whatever the mind can conceive and believe, it can achieve.<br><br>Napoleon Hill',
    'We become what we think about.<br><br>Earl Nightingale',
    'You can never cross the ocean until you have the courage to lose sight of the shore.<br><br>Christopher Columbus',
    'The two most important days in your life are the day you are born and the day you find out why.<br><br>Mark Twain',
    'The only person you are destined to become is the person you decide to be.<br><br>Ralph Waldo Emerson',
    'Everything you\'ve ever wanted is on the other side of fear.<br><br>George Addair',
    'Start where you are. Use what you have. Do what you can.<br><br>Arthur Ashe',
    'Your time is limited, so don\'t waste it living someone else\'s life.<br><br>Steve Jobs',
    'Winning isn\'t everything, but wanting to win is.<br><br>Vince Lombardi',
    'You never know how strong you are until being strong is the only choice you have.<br><br>Bob Marley',
    'A person who never made a mistake never tried anything new.<br><br>Albert Einstein',
    'I\'ve missed more than 9,000 shots in my career. I\'ve lost almost 300 games. Twenty-six times, I\'ve been trusted to take the game-winning shot and missed. I\'ve failed over and over and over again in my life—and that is why I succeed.<br><br>Michael Jordan',
    'If you want to make your dreams come true, the first thing you have to do is wake up.<br><br>J. M. Power',
    'Twenty years from now you will be more disappointed by the things you didn\'t do than by the ones you did do.<br><br>Mark Twain',
    'Work until your idols become your rivals.<br><br>Drake',
    'If you truly pour your heart into what you believe in, even if it makes you vulnerable, amazing things can and will happen.<br><br>Emma Watson',
    'Believe you can, and you\'re halfway there.<br><br>Theodore Roosevelt',
    'Happiness can be found, even in the darkest of times, if one only remembers to turn on the light.<br><br>Albus Dumbledore (Harry Potter and the Prisoner of Azkaban)',
    'It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.<br><br>Albus Dumbledore (Harry Potter and the Sorcerer\'s Stone)',
    'It is important to fight, and fight again, and keep fighting, for only then can evil be kept at bay, though never quite eradicated.<br><br>Albus Dumbledore (Harry Potter and the Half-Blood Prince)',
    'In the middle of every difficulty lies opportunity.<br><br>Albert Einstein',
    'There ain\'t no sin and there ain\'t no virtue. There\'s just stuff people do.<br><br>John Steinbeck (The Grapes of Wrath)',
    'Becoming fearless isn\'t the point. That\'s impossible. It\'s learning how to control your fear, and how to be free from it.<br><br>Veronica Roth (Divergent)',
    'Politeness is deception in pretty packaging.<br><br>Veronica Roth (Divergent)',
    'We are like butterflies who flutter for a day and think it is forever.<br><br>Carl Sagan',
    'I have never listened to anyone who criticized my taste in space travel, sideshows, or gorillas. When this occurs, I pack up my dinosaurs and leave the room.<br><br>Ray Bradbury',
    'Somewhere, something incredible is waiting to be known.<br><br>Carl Sagan',
    'Sadly, it is much easier to create a desert than a forest.<br><br>James Lovelock',
    'Life isn\'t about finding yourself. Life is about creating yourself.<br><br>George Bernard Shaw',
    'Success is not final, failure is not fatal: it is the courage to continue that counts.<br><br>Winston Churchill',
    'So we beat on, boats against the current, borne back ceaselessly into the past.<br><br>F. Scott Fitzgerald (The Great Gatsby)',
    'The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair, and though in all lands love is now mingled with grief, it grows perhaps the greater.<br><br>J. R. R. Tolkien (The Fellowship of the Ring)',
    'Never let your sense of morals prevent you from doing what is right.<br><br>Isaac Asimov',
    'If you can\'t fly, then run; if you can\'t run, then walk; if you can\'t walk, then crawl; but whatever you do, you have to keep moving forward.<br><br>Martin Luther King Jr.',
    'Earth provides enough to satisfy every man\'s need, but not every man\'s greed.<br><br>Mahatma Gandhi',
    'When you arise in the morning, think of what a privilege it is to be alive, to think, to enjoy, to love.<br><br>Marcus Aurelius',
    'We don\'t make mistakes—just happy little accidents.<br><br>Bob Ross',
    'You can be the best version of yourself, no matter what other people think.<br><br>Taylor Swift',
    'Curious that we spend more time congratulating people who have succeeded than encouraging people who have not.<br><br>Neil deGrasse Tyson',
    'Knowing how to think empowers you far beyond those who know only what to think.<br><br>Neil deGrasse Tyson',
    'We are stardust brought to life, then empowered by the universe to figure itself out—and we have only just begun.<br><br>Neil deGrasse Tyson',
    'I alone cannot change the world, but I can cast a stone across the water to create many ripples.<br><br>Mother Teresa',
    'Happiness is a butterfly which, when pursued, is always just beyond your grasp, but which, if you will sit down quietly, may alight upon you.<br><br>Nathaniel Hawthorne',
    'Cherish your visions and your dreams, as they are the children of your soul—the blueprints of your ultimate achievements.<br><br>Napoleon Hill',
    'The best and most beautiful things in the world cannot be seen or even touched—they must be felt with the heart.<br><br>Helen Keller',
    'Keep your face always toward the sunshine, and shadows will fall behind you.<br><br>Walt Whitman',
    'No matter what anybody tells you, words and ideas can change the world.<br><br>John Keating (Dead Poets Society)',
    'If opportunity doesn\'t knock, build a door.<br><br>Milton Berle',
    'Be a rainbow in somebody else\'s cloud.<br><br>Maya Angelou',
    'Someone\'s sitting in the shade today because someone planted a tree a long time ago.<br><br>Warren Buffett',
    'What lies behind us and what lies before us are tiny matters compared to what lies within us.<br><br>Henry Stanley Haskins',
    'Throw your dreams into space like a kite, and you do not know what it will bring back: a new life, a new friend, a new love, a new country.<br><br>Anaïs Nin',
    'Life itself is the most wonderful fairy tale.<br><br>Hans Christian Andersen',
    'Think of all the beauty still left around you and be happy.<br><br>Anne Frank',
    'Seize the moment, \'cause tomorrow you might be dead.<br><br>Buffy Summers (Buffy the Vampire Slayer)',
    'The hardest thing in this world is to live in it.<br><br>Buffy Summers (Buffy the Vampire Slayer)',
    'Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.<br><br>G. K. Chesterton',
    'Do not pray for an easy life; pray for the strength to endure a difficult one.<br><br>Bruce Lee',
    'Stay hungry, stay foolish.<br><br>Steve Jobs',
    'Laughter is timeless, imagination has no age, and dreams are forever.<br><br>Walt Disney',
    'The more you like yourself, the less you are like anyone else, which makes you unique.<br><br>Walt Disney',
    'Just be yourself; there is no one better.<br><br>Taylor Swift',
    'Fearless is not the absence of fear. It\'s not being completely unafraid. Fearless is living in spite of those things that scare you to death.<br><br>Taylor Swift',
    'Do, or do not. There is no try.<br><br>Yoda (Star Wars: The Empire Strikes Back)',
    'Act as if what you do makes a difference. It does.<br><br>William James',
    'Do not wait to strike till the iron is hot, but make it hot by striking.<br><br>Ralph Waldo Emerson',
    'Keep away from those who try to belittle your ambitions. Small people always do that, but the really great make you believe that you too can become great.<br><br>Mark Twain',
    'Go confidently in the direction of your dreams. Live the life you have imagined.<br><br>Henry David Thoreau',
    'The future belongs to those who believe in the beauty of their dreams.<br><br>Eleanor Roosevelt',
    'Do not go where the path may lead, go instead where there is no path and leave a trail.<br><br>Ralph Waldo Emerson',
    'Everything you can imagine is real.<br><br>Pablo Picasso',
    'Courage doesn\'t always roar. Sometimes courage is the quiet voice at the end of the day saying, "I will try again tomorrow."<br><br>Mary Anne Radmacher',
    'Act without expectation.<br><br>Lao Tzu',
    'Hope is the thing with feathers that perches in the soul, and sings the tune without the words, and never stops at all.<br><br>Emily Dickinson',
    'First say to yourself what you would be; and then do what you have to do.<br><br>Epictetus',
    'Light tomorrow with today.<br><br>Elizabeth Barrett Browning',
    'We are what we repeatedly do. Excellence, then, is not an act but a habit.<br><br>Will Durant (Aristotle)',
    'Act as though it were impossible to fail.<br><br>Dorothea Brande',
    'It is not the mountain we conquer, but ourselves.<br><br>Sir Edmund Hillary',
    'Energy and persistence conquer all things.<br><br>Benjamin Franklin',
    'A champion is defined not by their wins but by how they can recover when they fall.<br><br>Serena Williams',
    'He who has a why to live can bear almost any how.<br><br>Friedrich Nietzsche',
    'When I let go of what I am, I become what I might be.<br><br>Lao Tzu',
    'Be like a tree and let the dead leaves drop.<br><br>Rumi',
    'The impediment to action advances action. What stands in the way becomes the way.<br><br>Marcus Aurelius',
    'You can\'t put a limit on anything. The more you dream, the farther you get.<br><br>Michael Phelps',
    'I had to learn early on to believe in myself and I think that helped me a lot.<br><br>Serena Williams',
    'Your story is what you have, what you will always have. It is something to own.<br><br>Michelle Obama',
    'It\'s never too late to be what you might have been.<br><br>George Eliot',
    'When you have a dream, you\'ve got to grab it and never let go.<br><br>Carol Burnett',
    'I don\'t have big ideas. I sometimes have small ideas, which seem to work out.<br><br>Matt Damon',
    'Failure is not the opposite of success; it\'s part of success.<br><br>Arianna Huffington',
    'If you\'re always trying to be normal, you will never know how amazing you can be.<br><br>Maya Angelou',
    'Don’t be afraid. Be focused. Be determined. Be hopeful. Be empowered.<br><br>Michelle Obama',
    'Life\'s a garden: dig it.<br><br>Joe Dirt (Joe Dirt)',
    'You can\'t have no in your heart.<br><br>Joe Dirt (Joe Dirt)',
    'If you ain\'t first, you\'re last.<br><br>Ricky Bobby (Talladega Nights)',
    'Just keep swimming.<br><br>Dory (Finding Nemo)',
    'We don\'t make mistakes—just happy little accidents.<br><br>Bob Ross',
    'Get busy living or get busy dying.<br><br>Andy Dufresne (The Shawshank Redemption)',
    'The limit does not exist!<br><br>Cady Heron (Mean Girls)',
    'Strong is fighting. It\'s hard and it\'s painful, and it\'s every day. But it\'s what we have to do.<br><br>Buffy Summers (Buffy the Vampire Slayer)',
    'If nothing we do matters, then all that matters is what we do.<br><br>Angel (Angel)',
    'Heroes don\'t accept the world the way it is. They fight it.<br><br>Angel (Angel)',
    'Magic isn\'t just spells and potions. It\'s about believing in yourself.<br><br>Phoebe Halliwell (Charmed)',
    'Being normal is vastly overrated.<br><br>Piper Halliwell (Charmed)',
    'All we have to decide is what to do with the time that is given us.<br><br>Gandalf (The Fellowship of the Ring)',
    'Even the smallest person can change the course of the future.<br><br>Galadriel (The Fellowship of the Ring)'
];
